name = "Magnesium"
uuid = "a7f833be-55f5-4bd1-9de4-0975dc03b853"
authors = ["baedan <anarchotransformer@proton.me> and contributors"]
version = "1.0.0-DEV"

[deps]
Overseer = "1ada24be-c16d-4464-9f61-27c2e0f16645"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Overseer = "0.3.2"
julia = "1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
